apiVersion: v1
kind: Service
metadata:
  name: platforms-node-port-service
spec:
  type: NodePort
  selector:
    app: platformsservice
  ports:
    - name: platformsservice
      protocol: TCP
      port: 80
      targetPort: 80
      